version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
    networks:
      - mynetwork
    # volumes:
    # - .:/app
  worker:
    build: .
    command: rq worker
    depends_on:
      - redis
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
    networks:
      - mynetwork
  redis:
    image: "redis:latest"
    networks:
      - mynetwork

networks:
  mynetwork:
