version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - RQ_REDIS_URL=${REDIS_URL}
    networks:
      - mynetwork
  worker:
    build: .
    volumes:
      - .:/app
    command: python worker.py
    depends_on:
      - redis
    environment:
      - RQ_REDIS_URL=${REDIS_URL}
    networks:
      - mynetwork
  redis:
    image: "redis:latest"
    networks:
      - mynetwork

networks:
  mynetwork:
